---
- hosts: target
  tasks:
  - name: configure interface file
    copy:
       src: ./interfaces
       dest: /etc/network/interfaces
       owner: root
       group: root
       mode: u=rw,g=r,o=r

  - name: add line to apt sources.list
    lineinfile:
      dest: /etc/apt/sources.list
      line: "deb http://ftp.debian.org/debian jessie-backports main"

  - name: Update and Upgrade all packages to the latest version
    apt:
      upgrade: dist
      update_cache: yes

  - name: Install Required packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - screen
      - vim
      - drbd-utils
      - ganeti-instance-debootstrap
      - qemu-kvm
      - ethtool
      - ntp
      - openvswitch-switch
      - ganeti

  - name: install ganeti from backports
    apt:
      name: ganeti
      state: latest
      default_release: jessie-backports
    tags:
      - run

  - name: ensure drbd.conf exists
    copy:
      content: ""
      dest: /etc/modprobe.d/drbd.conf
      force: no
      group: root
      owner: root
      mode: 644

  - name: add line to drbd.conf
    lineinfile:
      dest: /etc/modprobe.d/drbd.conf
      line: 'options drbd minor_count=128 usermode_helper=/bin/true'

  - name: add line to /etc/modules
    lineinfile:
      dest: /etc/modules
      line: 'drbd'

  - name: Probing all modules
    command: "/sbin/depmod -a"

  - name: Add DRBD Module
    command: "/sbin/modprobe drbd"

  - name: Restart lvm2
    service:
      name: lvm2
      state: restarted

  - name: Creating SymLinks for kernel images
    file:
      src: "{{ item.path }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { path: '/boot/vmlinuz-3.16.0-4-amd64', dest: '/boot/vmlinuz-3-kvmU' }
      - { path: '/boot/initrd.img-3.16.0-4-amd64', dest: '/boot/initrd-3-kvmU' }

  - name: remove apt dependancies # APT Module gives error, using command directly instead
    command: apt-get autoremove -y


  - name: copy interfaces file modification script to remote server
    copy:
       src: ./modinterfaces.sh
       dest: /root/modinterfaces.sh
       owner: root
       group: root
       mode: u=rw,g=r,o=r

  - name: execute interfaces modification script
    command: "bash /root/modinterfaces.sh"

  - name: restart machine
    command: reboot


...
